name: Test, Build and Deploy |  Modul 1 lab2.2 Senior Project

on: 
  push:
    branch: [main]

jobs: 
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            eval "${ssh-agent -s}"
            ssh-add ~/.ssh/senpro-ssh
            cd ~/senpro/460537/modul01/senpro-github-action
            git restore .
            git pull origin main
            npm install
            npm run build
